// <auto-generated />
using System;
using DocumentationCompleteness.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocumentationCompleteness.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310204008_AddLanguageAndSnippetToGap")]
    partial class AddLanguageAndSnippetToGap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentationCompleteness.Api.Models.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Log")
                        .HasColumnType("text")
                        .HasColumnName("log");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("analysis_jobs");
                });

            modelBuilder.Entity("DocumentationCompleteness.Api.Models.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnalyzedFiles")
                        .HasColumnType("integer")
                        .HasColumnName("analyzed_files");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CriticalGaps")
                        .HasColumnType("integer")
                        .HasColumnName("critical_gaps");

                    b.Property<int>("HighPriorityGaps")
                        .HasColumnType("integer")
                        .HasColumnName("high_priority_gaps");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("LowPriorityGaps")
                        .HasColumnType("integer")
                        .HasColumnName("low_priority_gaps");

                    b.Property<int>("MediumPriorityGaps")
                        .HasColumnType("integer")
                        .HasColumnName("medium_priority_gaps");

                    b.Property<double>("OverallCoverage")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_coverage");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer")
                        .HasColumnName("total_files");

                    b.Property<int>("TotalGaps")
                        .HasColumnType("integer")
                        .HasColumnName("total_gaps");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("analysis_results");
                });

            modelBuilder.Entity("DocumentationCompleteness.Api.Models.DocumentationGap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeSnippet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_snippet");

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_name");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_type");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("GapType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gap_type");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MissingCoverageType")
                        .HasColumnType("text")
                        .HasColumnName("missing_coverage_type");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("ResultId");

                    b.ToTable("documentation_gaps");
                });

            modelBuilder.Entity("DocumentationCompleteness.Api.Models.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_branch");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_url");

                    b.Property<string>("ScanFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scan_frequency");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("repositories");
                });

            modelBuilder.Entity("DocumentationCompleteness.Api.Models.AnalysisJob", b =>
                {
                    b.HasOne("DocumentationCompleteness.Api.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DocumentationCompleteness.Api.Models.AnalysisResult", b =>
                {
                    b.HasOne("DocumentationCompleteness.Api.Models.AnalysisJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentationCompleteness.Api.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DocumentationCompleteness.Api.Models.DocumentationGap", b =>
                {
                    b.HasOne("DocumentationCompleteness.Api.Models.AnalysisJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentationCompleteness.Api.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentationCompleteness.Api.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("Gaps")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");

                    b.Navigation("Job");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DocumentationCompleteness.Api.Models.AnalysisResult", b =>
                {
                    b.Navigation("Gaps");
                });
#pragma warning restore 612, 618
        }
    }
}
